### ISSUE TITLE
Authentication sample

### ISSUE THREAD

**Issue by fabioluz** [PWKad/aurelia-samples#4]
Hi, 

Could you create a sample with authentication, authorization and a basic CRUD (only client of course)? 

Congratulations for your work so far!

Thank you!

**Comment by bastienJS** [comment]
I can just second that request. I would also appreciate a sample showing kind of "angular" interceptor for authorization doing in the aurelia way of course with Login screen.

**Comment by gavinaiken** [comment]
Another vote for this. Login & CRUD are very likely to be the first things a dev wants to do with any app, and a sample showing a nice way to do this would be great.

**Comment by plwalters** [comment]
Definitely noted, this weekend I will update to the latest skeleton and will get a simple OAuth login sample published as well.

**Comment by bastienJS** [comment]
Can`t wait :-)

**Comment by ChrisMancini** [comment]
Would really love to see this as well....

**Comment by dotnetrules** [comment]
:+1:   Me too.....and in addition I was also looking for something similar to Durandal's router guardRoute as I and others will have Durandal apps to migrate. :-D

**Comment by fabarea** [comment]
:+1:

**Comment by jwtvh** [comment]
Would be great!

**Comment by cmichaelgraham** [comment]
:+1:

**Comment by ChrisMancini** [comment]
This looks interesting...

https://github.com/paulvanbladel/aureliauth

**Comment by bakanis** [comment]
Hi, I'm new to nodejs and SPA so don make fun of me. But is it me or do you noticed that if aurelia sample app is open from a mobile device and on another device on the same LAN then the smae menu open from one window will be opened on another device as well and otherwise. In this case users will make it difficult to browse to each other.

**Comment by wshayes** [comment]
It's the wonders of browsersync: http://www.browsersync.io  It's started as part of gulp watch  - makes dev work on multiple browsers much easier.

**Comment by bakanis** [comment]
Thank you. I was afraid I found a nasty bug..

**Comment by plwalters** [comment]
After all the +1's I figure it's about time.  I'll add an example using @paulvanbladel 's aureliaauth as mentioned earlier this week.
