### ISSUE TITLE
The buttons in the modal don't work

### ISSUE THREAD

**Issue by wichert** [PWKad/aurelia-samples#5]
Clicking the "X" in the top right corner works fine, but clicking either the close or the save button doesn't do anything.

**Comment by plwalters** [comment]
Yeah this was a very basic sample to give a starting point for developers to use.  I will get it updated this weekend and make sure all of the samples are at least demonstrating points we want to show off.  thanks!

**Comment by plwalters** [comment]
This should be fixed now actually since the modal has been extracted.
